-- CreateTable
CREATE TABLE "ROLE" (
    "id" INTEGER NOT NULL,
    "label" VARCHAR(100) NOT NULL,

    CONSTRAINT "ROLE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER_ACCOUNT" (
    "id" VARCHAR(50) NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "role_id" INTEGER NOT NULL,
    "program" VARCHAR(150),
    "whitelisted" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "USER_ACCOUNT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DOCUMENT" (
    "id" VARCHAR(50) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "student_id" VARCHAR(50) NOT NULL,
    "adviser_id" VARCHAR(50),
    "status" VARCHAR(50) NOT NULL,
    "mode" INTEGER,
    "submitted_date" TIMESTAMP(3) NOT NULL,
    "updated_date" TIMESTAMP(3) NOT NULL,
    "remarks" TEXT,

    CONSTRAINT "DOCUMENT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DOCUMENT_HISTORY" (
    "id" SERIAL NOT NULL,
    "document_id" VARCHAR(50) NOT NULL,
    "status" VARCHAR(50) NOT NULL,
    "actor_id" VARCHAR(50) NOT NULL,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DOCUMENT_HISTORY_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_ACCOUNT_email_key" ON "USER_ACCOUNT"("email");

-- AddForeignKey
ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "USER_ACCOUNT_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "ROLE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "USER_ACCOUNT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_adviser_id_fkey" FOREIGN KEY ("adviser_id") REFERENCES "USER_ACCOUNT"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_HISTORY" ADD CONSTRAINT "DOCUMENT_HISTORY_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "DOCUMENT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_HISTORY" ADD CONSTRAINT "DOCUMENT_HISTORY_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "USER_ACCOUNT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
